apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiapp-deployment
  namespace: apiapp
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: echoserver-container
        image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: Always
        ports:
        - containerPort: 32134