apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiapp-deployment
  namespace: apiapp
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: echoserver-container
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080