apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiapp-deployment
  namespace: apiapp
  labels:
    app: apiapp
    type: api
spec:
  template:
    metadata:
      name: apiapp-pod
      labels:
        app: apiapp
        type: api
    spec:
      containers:
      - name: echoserver-container
        image: gcr.io/google_containers/echoserver:1.4
        ports:
          - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      type: api