apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticapp-deployment
  namespace: staticapp
spec:
  selector:
    matchLabels:
      app: static
  replicas: 2
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: nginx-container
        image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080