apiVersion: v1
kind: Service
metadata:
  name: static-service
  namespace: staticapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: static