apiVersion: v1
kind: Service
metadata:
  name: static-service
  namespace: staticapp
spec:
  ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
  type: NodePort
  selector:
    app: static