apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marfeel-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JuanAlcina/Marfeel-IaC.git
    targetRevision: HEAD
    path: manifests/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: api_app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true