apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-app
  namespace: apiapp
spec:
  project: default
  source:
    repoURL: https://github.com/JuanAlcina/Marfeel-IaC.git
    targetRevision: ${env}
    path: manifests/apps/api
  destination:
    server: https://kubernetes.default.svc
    namespace: apiapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true