apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-html-configmap
  namespace: staticapp
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file </h1>
    </html