apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: marfeel-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /api
          backend:
            serviceName: api-service
            servicePort: 4200