apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-app
  namespace: staticapp
spec:
  project: default
  source:
    repoURL: https://github.com/JuanAlcina/Marfeel-IaC.git
    targetRevision: HEAD
    path: manifests/apps/static
  destination:
    server: https://kubernetes.default.svc
    namespace: staticapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true